function sizeOfMatrix = ott_tmatrix_from_mstm(fname)
% Read in tmatrix output file generated by mstm and rearrange into
% ott order.
% Inputs: 
%     fname : path to T matrix file generated by mstm
% Author: Wyatt Vigilante
% Bug fix 2026-10-06: by inspection of mstm source (readtmatrix in mstm-modules-v3.0.f90), 
% with T_(nmp lkq), for each column (l,k,q), mstm only writes rows 
% from n = 1 to l (in effect, half the T-matrix). There is a reciprocity
% relation to be used to reconstruct elements:
% T[row (l, -k, q); col (n, -m, p)] = (-1)^(m+k) * T[row (n, m, p); col (l, k, q)]
% for n < l.
% Filling with this reciprocity relation only applies 
% when first header integer (rhscondition) is not 0. 
% Otherwise, mstm writes all T matrix elements.

global Tmatrix;

fileID = fopen(fname, 'r') ;

% Read top line from file, keeping newline
tline = fgets(fileID);
tline = str2num(tline); %
fillReciprocal = (tline(1) == 0); % need to fill in rows truncated at n <= l
sizeOfMatrix = tline(2); % This is the max order of the expansion (nodrt)
subMatrixSize = (sizeOfMatrix^2) + (2 * sizeOfMatrix); % nmax^2 + 2nmax

% Allocate storage for data
% the order in which these quadrants are named is exactly as a cartesian grid
% [[II, I], [III, IV]]
firstQuad = zeros(subMatrixSize, subMatrixSize); % T^{12}
secondQuad = zeros(subMatrixSize, subMatrixSize); % T^{11}
thirdQuad = zeros(subMatrixSize, subMatrixSize); % T^{21}
fourthQuad = zeros(subMatrixSize, subMatrixSize); % T^{22}

line2 = fgets(fileID); % Read line 2 of file; not used.

% Main loop to construct T-matrix by reading file line-by-line, 
% starting from line 3.
% mstm elements are T_{mnpklq}
% ott elements are T_{n,m,nprime,mprime}
while ~feof(fileID)
  line = fgets(fileID); % Read next line
  numLine = str2num(line);
  
  if length(numLine) == 3 % Line is l, k, q
     l = numLine(1);
     nprime = l;
     k = numLine(2);
     mprime = k;
     q = numLine(3);
     colPosInSubMatrix = ott.utils.combined_index(nprime,mprime); %calculating column position
  elseif length(numLine) == 4 % line is scattering efficiency convergence checks
     % do nothing
  elseif length(numLine) == 6 % line has T matrix data
     n = numLine(1);
     m = numLine(2);
     rowPosInSubMatrix = ott.utils.combined_index(n,m);
     realPFirst = numLine(3); % p = 1
     imaginaryPFirst = numLine(4);
     realPSecond = numLine(5); % p = 2
     imaginaryPSecond = numLine(6);
     val1 = realPFirst + imaginaryPFirst*i;
     val2 = realPSecond + imaginaryPSecond*i;
     if q == 1 
         % T^{22}
         fourthQuad(rowPosInSubMatrix,colPosInSubMatrix) = val1;
         % T^{12}
         firstQuad(rowPosInSubMatrix,colPosInSubMatrix) = val2;
     else % q = 2
         % T^{21}
         thirdQuad(rowPosInSubMatrix,colPosInSubMatrix) = val1;
         % T^{11}
         secondQuad(rowPosInSubMatrix,colPosInSubMatrix) = val2; 
     end
     % fill in reciprocal elements with n > l if needed
     if fillReciprocal && n < l 
         sgn = (-1) ^ (m+k);
         rowR = ott.utils.combined_index(l, -k);
         colR = ott.utils.combined_index(n, -m);
         if q == 1
             fourthQuad(rowR, colR) = sgn * val1; % T22
             thirdQuad(rowR, colR) = sgn * val2; % T21
         else
             firstQuad(rowR, colR) = sgn * val1; % T12
             secondQuad(rowR, colR) = sgn * val2; % T11
         end
     end  
  end     
end

Tmatrix_data = [secondQuad, firstQuad ; thirdQuad, fourthQuad];
Tmatrix = ott.Tmatrix(Tmatrix_data, 'scattered');

fclose(fileID);

end

